import{a as E,S as q,i as m}from"./assets/vendor-CNqCr-V-.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))r(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function s(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function r(o){if(o.ep)return;o.ep=!0;const n=s(o);fetch(o.href,n)}})();const S="https://pixabay.com/api/",v="53387136-aec480b6b069bc63c101bbeda",h=15;async function y(t,e=1){const s=t.trim();if(!s)throw new Error("Empty search query");try{const{data:r}=await E.get(S,{params:{key:v,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:h,page:e}});return r}catch(r){throw r.response?new Error(`API error: ${r.response.status} ${r.response.statusText}`):r.request?new Error("Network error: no response from server"):new Error(r.message)}}let d=null;function g(t){const e=document.querySelector(".gallery"),s=t.map(({webformatURL:r,largeImageURL:o,tags:n,likes:a,views:w,comments:L,downloads:b})=>`
<li class="gallery-item">
  <a class="gallery-link" href="${o}">
    <img class="gallery-image" src="${r}" alt="${n}" />
  </a>
  <div class="info">
    <p class="info-item">Likes: <span class="info-span">${a}</span></p>
    <p class="info-item">Views: <span class="info-span">${w}</span></p>
    <p class="info-item">Comments: <span class="info-span">${L}</span></p>
    <p class="info-item">Downloads: <span class="info-span">${b}</span></p>
  </div>
</li>`).join("");e.insertAdjacentHTML("beforeend",s),d?d.refresh():d=new q(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"})}function P(){document.querySelector(".gallery").innerHTML=""}function u(t){const e=document.querySelector(".loader");e&&(t?e.classList.remove("hidden"):e.classList.add("hidden"))}function c(t){const e=document.querySelector(".load-more");e&&(t?e.classList.remove("hidden"):e.classList.add("hidden"))}const $=document.querySelector(".form"),B=document.querySelector(".load-more");let p="",i=1,l=0;$.addEventListener("submit",A);B.addEventListener("click",I);function f(t){m.error({title:"Помилка",message:t,position:"topRight",timeout:3e3})}async function A(t){t.preventDefault();const e=t.target.elements.searchQuery.value.trim();if(!e){f("Будь ласка, введіть пошуковий запит");return}p=e,i=1,l=0,P(),u(!0);try{const s=await y(p,i);if(!s.hits.length){f("Немає зображень за вашим запитом."),c(!1);return}l=s.totalHits,g(s.hits);const r=i*h<l;c(r),r||m.info({title:"Info",message:"Ви переглянули всі результати.",position:"topRight"})}catch(s){f("Помилка: "+s.message),c(!1)}finally{u(!1)}}async function I(){i+=1,u(!0);try{const t=await y(p,i);g(t.hits);const e=i*h<l;c(e),e||m.info({title:"Info",message:"Ви переглянули всі результати.",position:"topRight"});const s=document.querySelector(".gallery .gallery-item");if(s){const{height:r}=s.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}}catch(t){f("Помилка: "+t.message)}finally{u(!1)}}
//# sourceMappingURL=index.js.map
