import{a as E,S as q,i as h}from"./assets/vendor-CNqCr-V-.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const v="https://pixabay.com/api/",S="53387136-aec480b6b069bc63c101bbeda",m=15;async function y(t,n=1){const o=t.trim();if(!o)throw new Error("Empty search query");try{const{data:s}=await E.get(v,{params:{key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:m,page:n}});return s}catch(s){throw s.response?new Error(`API error: ${s.response.status} ${s.response.statusText}`):s.request?new Error("Network error: no response from server"):new Error(s.message)}}let d=null;function g(t){const n=document.querySelector(".gallery"),o=t.map(({webformatURL:s,largeImageURL:e,tags:r,likes:i,views:L,comments:w,downloads:b})=>`
<li class="gallery-item">
  <a class="gallery-link" href="${e}">
    <img class="gallery-image" src="${s}" alt="${r}" />
  </a>
  <div class="info">
    <p class="info-item">Likes: <span class="info-span">${i}</span></p>
    <p class="info-item">Views: <span class="info-span">${L}</span></p>
    <p class="info-item">Comments: <span class="info-span">${w}</span></p>
    <p class="info-item">Downloads: <span class="info-span">${b}</span></p>
  </div>
</li>`).join("");n.insertAdjacentHTML("beforeend",o),d?d.refresh():d=new q(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"})}function P(){document.querySelector(".gallery").innerHTML=""}function f(t){document.querySelector(".loader").classList.toggle("hidden",!t)}const $=document.querySelector(".form"),c=document.querySelector(".load-more");let p="",a=1,l=0;$.addEventListener("submit",A);c.addEventListener("click",O);function u(t){h.error({title:"Помилка",message:t,position:"topRight",timeout:3e3})}async function A(t){t.preventDefault();const n=t.target.elements.searchQuery.value.trim();if(!n){u("Будь ласка, введіть пошуковий запит");return}p=n,a=1,l=0,P(),c.classList.add("hidden"),f(!0);try{const o=await y(p,a);if(!o.hits.length){u("Sorry, there are no images matching your search query.");return}l=o.totalHits,g(o.hits),a*m<l&&c.classList.remove("hidden")}catch(o){u("Помилка: "+o.message)}finally{f(!1)}}async function O(){a+=1,c.classList.add("hidden"),f(!0);try{const t=await y(p,a);g(t.hits),a*m<l?c.classList.remove("hidden"):h.info({title:"Info",message:"You've reached the end of the results.",position:"topRight"})}catch(t){u("Помилка: "+t.message)}finally{f(!1)}}
//# sourceMappingURL=index.js.map
